version: '3.6'

services:
  studbaza.webapi:
    image: randomdocker729/cidashboard-webapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development